Page multimédia
Jonathan-08/MangAnnuaire pull request #33
Opened 2024-02-02 00:38 UTC by ChrisMBA

Page Multimédia

### Description
Ajout des éléments sur la page multimédia

## Changements proposés
Fanart et Interview

2024-02-02 17:12 UTC, Jonathan-08 requested changes
Il y a juste le petit lien à changer sur la ligne 9 du fichier header.js

2024-02-02 17:12 UTC, Jonathan-08 commented on header.js
> +        <li><a href="#multimedia.html">Multimédia</a></li>
Il faut que tu retire le # pour le lien chef! À part ça je pense que ça sera bon.

2024-02-02 19:44 UTC, ChrisMBA commented on header.js
> +        <li><a href="#multimedia.html">Multimédia</a></li>
Ok je fait ça

2024-02-02 20:07 UTC, Jonathan-08 reviewed
C'est bon, j'approuve cette version

2024-02-02 20:07 UTC, Jonathan-08 approved these changes
J'approuve

2024-02-02 20:31 UTC, closed without merging

2024-02-16 18:39 UTC, Pyracantharia commented
j'approuve pas

2024-02-16 18:40 UTC, Pyracantharia commented
j'approuve pas

2024-02-16 18:40 UTC, Jonathan-08 commented
Je n'approuve pas

2024-02-16 18:40 UTC, Pyracantharia commented
J'approuve pas

2024-02-16 18:41 UTC, Pyracantharia commented
Il y un soucis sur le front